import './globals.css'
import { Montserrat } from 'next/font/google'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: '400'
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">      
      <body className={montserrat.className}>{children}</body>
    </html>
  )
}
